### ISSUE TITLE
Bug in InsertMissingDictionary and GetDictionaries

### ISSUE THREAD

**Issue by tleclaire** [arduosoft/HubLink#7]
There seems to be a bug in the method InsertMissingDictionary where it tries to insert every entry with the name 'MAIN' wich does not work due to duplicate key constarint aon the table.
The GetDictionaries method in DBKeyPairRepository seems also not implemented properly since the first query by ApplicationId gets always overwridden by the second by Name.
This leads to a crowded log. 
Not sure what the Dictionary is used for anyway.

**Comment by zeppaman** [comment]
Thanks for detailed report. I'll check and give you a feedback.

**Comment by zeppaman** [comment]
Hi @tleclaire 
I start from the last point:

**Not sure what the Dictionary is used for anyway.**
Hublink dictionaries are remote dictionary used to share data across client applications. This feature will allow user to create more than one dictionary for each application. This means you can manage multiple set of data. As for all other entities in Hublink application is the tenant so each application can have it's own dictionaries.

**index issues**
It was a bug on index definition. There should be an index that allow unique names inside same application, but there was just a simple index on name column. This doesn't allow generation of default dictionary for app (that have to be always present) and it was a problem. fixed changed index. It may be needed to remove wrong index manully basing on database you are using to apply the patch.

**GetDictionaries method in DBKeyPairRepository**
It is correct to apply both filters. ApplicationId limit search on application scope meanwhile name filter repository by name, keeping aplicationId not null expose to a bad usage from caller, but for what I see (and I test) all seems right.

Hublink was fixed and this will released with a minor. 
Please let me know in which context you are using ( production, test, just downloaded to test..) so that I may suggest best update strategy.

**Comment by tleclaire** [comment]
Hi @zeppaman ,
thanks for your reply.
I'm still not sure about the use case of the dictionary. What does it have to do with logging?
We are using it actually in production of our SharePoint based solutions to have a logging component separated from the SharePoint ULS logs which has just to much content and is difficult to access.
Works great and is easy to implement. I only removed the full text index which I see as not helpfull when a simple database query does the job.

**Comment by zeppaman** [comment]
Hi @tleclaire 
Hublink is designed to be more than a log collecting system. Since the first implementation we understood that there are to many free\opensource log collector tools to be competitive. Still today to do simply log colletting using kibana with log stash is the simpler alternative to get a vertical tool widely used and performant. 

That's why we think about a system that will give many functionalities as a service in one single tool. Full text searc, log collecting, remote dictionary, caching, translation all such feature are needed in an nowadays application and employ single separated system may be expensive (on premise ha maintenance recurrent cost like SaaS). Hublink want to be a service collector where, in a single UI, you can managa all this features for all application you have. This will break costs as you have only one system and make easy integration (all app start with all systems integration capabilities).

Actually Hublink expose only logging feature, but is mostly ready to go on with other features and or goal is to add them progressively. 

Of course, if you are interested only in logs, what you have is enough, but if log is only what you need a company wide installtion o kibana or remote service like logly may be a free alternative.

Regarding sharepoint I'm curious about how to send logs to external system (please answer only if you fell free...). Do you used a remote agent to send log file content to Hublink or implemented custom logger to send only logs into your customization? and in case how?

**Comment by zeppaman** [comment]
HI @tleclaire 
can I mark this issue as closed?

**Comment by tleclaire** [comment]
Sorry, was rather busy last week. Yes, please close it.
Regarding SharePoint, we are using a custom logger based on NLog and only logging from our solutions, which was the intention since SharePoint ULS Log is too hard to monitor. From our point of view, logging is the only thing we need, everything else could be achived with SharePoinr functionallities.
Regards
Thomas

**Comment by zeppaman** [comment]
Hi @tleclaire 
Thanks for submitting the issue and providing  such feedbacks.

Issue closed.
